### ISSUE TITLE
'Resize' object has no attribute 'max_size'

### ISSUE THREAD

**Issue by gauravsangwan** [danielroich/Face-Identity-Disentanglement-via-StyleGan2#4]
In Inception.py in line 21 there is an error which says "'Resize' object has no attribute 'max_size'", How to resolve this? @danielroich

**Comment by JIaqiYang78** [comment]
I have the same question with you, and did you solve it now?

**Comment by JIaqiYang78** [comment]
> In Inception.py in line 21 there is an error which says "'Resize' object has no attribute 'max_size'", How to resolve this? @danielroich

I have the same question with you, and did you solve it now?

**Comment by JIaqiYang78** [comment]
> > In Inception.py in line 21 there is an error which says "'Resize' object has no attribute 'max_size'", How to resolve this? @danielroich
>  it seems that your torch and torchvision version is not satisfied with the project used, you can see the environment.yml for correct version.

**Comment by gauravsangwan** [comment]
@JIaqiYang78  
No, I wasn't able to solve it even after installing the same version of torch and torchvision, still looking for the solution.

**Comment by winterplayer** [comment]
Hello！I have the same problem about it.Did you deal with it?

> @JIaqiYang78 No, I wasn't able to solve it even after installing the same version of torch and torchvision, still looking for the solution.
